### ISSUE TITLE
RSS Feed Missing

### ISSUE THREAD

**Issue by danieleagle** [grommet/grommet-blog#130]
I'm one of those people who likes to pull in RSS feeds into Outlook or any RSS reader for that matter. It would be nice to be able to do this with the Grommet blog so as to stay up to date on the latest news a little easier.

**Comment by alansouzati** [comment]
Thanks for reporting this. I will investigate that

**Comment by tracybarmore** [comment]
Will be working on this while implementing the grommet blog redesign. #129

**Comment by L0ZZI** [comment]
Hey @GetchaDEAGLE we'll be sunsetting the blog for grommet and using a new method to aggregate news around grommet—Stay tuned. If we use some form of syndication it's high on my list (I am one of those folks that reads the web via RSS too).
