### ISSUE TITLE
copy & links in blog header hard to read

### ISSUE THREAD

**Issue by djksar** [grommet/grommet-blog#42]
in the previous version of the blog we had the blog post title, author name and addthis link in a white box underneath the header image. Now it is over-layed on-top of the header image and hard to read.

What it looks like:
![](https://cloud.githubusercontent.com/assets/5169327/14567669/17215aca-02ea-11e6-96af-7014cdce88ee.png)

What the comparable post looks like on the current blog:
![](https://cloud.githubusercontent.com/assets/5169327/14567880/13dc00b2-02eb-11e6-91be-2d4c24e9a6b7.png)

**Comment by alansouzati** [comment]
when I said it is the same issue, I meant about the Grommet blog home page. Sorry if I was not clear.

![screen shot 2016-04-15 at 2 40 10 pm](https://cloud.githubusercontent.com/assets/1207250/14569915/f9784e74-0317-11e6-9a6e-bf4d082e28bf.png)

I believe this is an issue with both blogs and needs to be fixed.

**Comment by djksar** [comment]
i'm talking about the blog post page not the blog homepage.

**Comment by alansouzati** [comment]
After talking with Chris and Bryan we decided to live with that for now until we redesign the blog.

We are trying to stick with the native grommet styling, and playing with the position so that it floats over the image is something we are trying to avoid.

**Comment by alansouzati** [comment]
After talking with Randy, we are going to fix that before the release.

**Comment by alansouzati** [comment]
This is going to take longer than I expected. we need new images to respond better without being a background image.

We can live with that for now, @bryanjacquot is ok with that.

In the meantime I will try to work with Chris and Tracy to get better images for the blog posts.

**Comment by bryanjacquot** [comment]
Will address as part of https://github.com/grommet/grommet-blog/issues/129
