### ISSUE TITLE
status of search results should reflect action

### ISSUE THREAD

**Issue by djksar** [grommet/grommet-blog#45]
when I clicked on Bryan's name the search results refreshed with only his posts but would be nice to have the search box or some header copy updated with what the search results are showing. Does that make sense? Let me know.

**Comment by alansouzati** [comment]
Makes fully sense let me work on that!

**Comment by alansouzati** [comment]
Actually I was testing this issue and I don't think it applies to us.

If you click on Bryan's name I'm assuming you want to see the Archive for his posts. If you want a global search, then you can click on search to look for Bryan in any field.

This is using the same implementation as the current blog (http://blog.grommet.io) which I believe is the right way moving forward.
