### ISSUE TITLE
The placement of the add image button and add post buttons is potentially confusing

### ISSUE THREAD

**Issue by MisterHarris** [grommet/grommet-blog#47]
When creating a post, the publish button, labeled "Add," is directly below the Images label. New editors are likely to thing the "Add" button is for adding images, not for Publishing the post. The + button for adding images is far to the right of the image label and so easy to miss.

Recommendations: 
- Change "Add" to "Publish Post" or similar
- Move the + sign close to "Images"

<img width="832" alt="screen shot 2016-04-20 at 3 55 47 pm" src="https://cloud.githubusercontent.com/assets/18581856/14688561/396176da-0711-11e6-8b0c-2a61ee3d66ce.png">

**Comment by alansouzati** [comment]
good one. i will make sure to remove the confusion.

**Comment by alansouzati** [comment]
fixed.
