### ISSUE TITLE
Editing a post in April pushed April down to the bottom of the Manage screen

### ISSUE THREAD

**Issue by MisterHarris** [grommet/grommet-blog#52]
I edited the "Top 5 Rules for Giving Enterprise Apps a Consumer-Grade UX" post, which added it to the Pending Review queue. 

When I returned to the Manage screen, April content was at the bottom, rather than the top, as the most recent content. 
<img width="1194" alt="screen shot 2016-04-20 at 4 21 03 pm" src="https://cloud.githubusercontent.com/assets/18581856/14689160/27a7647e-0714-11e6-8c2c-70c1061a9b96.png">

**Comment by alansouzati** [comment]
good catch!

**Comment by MisterHarris** [comment]
Thanks, Alan!

**Comment by alansouzati** [comment]
fixed.
