### ISSUE TITLE
Table markdown doesn't create rows, columns, or cells. 

### ISSUE THREAD

**Issue by MisterHarris** [grommet/grommet-blog#53]
I tested this markdown for tables (from: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables )

| Tables | Are | Cool |
| --- | :-: | --: |
| col 3 is | right-aligned | $1600 |
| col 2 is | centered | $12 |
| zebra stripes | are neat | $1 |

And this:

| Markdown | Less | Pretty |
| --- | --- | --- |
| _Still_ | `renders` | **nicely** |
| 1 | 2 | 3 |

In Preview, it showed up as in the attached images, rather than showing the formatted table. Should table formatting be included 
<img width="313" alt="screen shot 2016-04-20 at 4 49 33 pm" src="https://cloud.githubusercontent.com/assets/18581856/14690101/6bcb193a-0718-11e6-81f1-a565425952ab.png">
<img width="347" alt="screen shot 2016-04-20 at 4 53 37 pm" src="https://cloud.githubusercontent.com/assets/18581856/14690110/7919ac46-0718-11e6-99c6-63d08fea8caf.png">

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/14b31bb939d9e6437cd975739614ceec1f9e4678

Markdown tables will now use Grommet tables: http://www.grommet.io/docs/develop/table
