### ISSUE TITLE
URLs from existing blog should work with new blog.

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet-blog#94]
Since there are references to Grommet blog posts on social media and elsewhere, it's important for URLs on the existing blog to continue to work.

Current blog URL
`/2016/04/08/top-5-rules-for-giving-enterprise-apps-a-consumer-grade-ux/`

Grommet blog URL
`/post/2016/04/08/top-5-rules-for-giving-enterprise-apps-a-consumer-grade-ux`

The Grommet blog's URLs start with `/post` which is not present on the existing blog.

**Comment by alansouzati** [comment]
FIxed.
